const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});

// MongoDB duplicate key error code.
const MONGO_DUPLICATE_KEY_ERROR = 11000;

module.exports = { HTTP_STATUS, MONGO_DUPLICATE_KEY_ERROR };
